# Generated by Django 5.0.6 on 2024-08-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_academicsession_options_and_more"),
        ("scholar_register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="branch",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
    ]
