# Generated by Django 5.0.6 on 2024-08-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0003_section_branch"),
        ("scholar_register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_standard",
                to="institute.standard",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_student",
                to="scholar_register.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_subject",
                to="institute.subjects",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
