# Generated by Django 5.0.1 on 2024-09-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scholar_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentComplaintsOrSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint')], max_length=200)),
                ('suggestion_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint')], max_length=200)),
                ('query', models.TextField(max_length=1000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_complaint_branch', to='accounts.institutebranch')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_complaint_institute', to='accounts.institute')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_complaint_session', to='accounts.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_complaint_student', to='scholar_register.studentprofile')),
            ],
        ),
    ]
