# Generated by Django 5.0.6 on 2024-07-17 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0003_rename_description_notificationmodel_description"),
        ("scholar_register", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="child_status",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="discount_scheme",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="fahers_aadhar_no",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="father_annual_income",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="father_pan_no",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="father_qualification",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="fathers_email",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="fathers_mob_no",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="fathers_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="fathers_occupation",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="fee_deposited_by",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="guardian_mobile",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="guardian_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="guardian_relation",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="mother_annual_income",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="mother_pan_no",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="mother_qualification",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="mothers_aadhar_no",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="mothers_email",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="mothers_mob_no",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="mothers_name",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="mothers_occupation",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="sms_mob_no",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="student_type",
        ),
        migrations.CreateModel(
            name="StudentParents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fathers_name", models.CharField(max_length=255)),
                ("fathers_email", models.CharField(blank=True, max_length=255)),
                ("fathers_mob_no", models.CharField(max_length=255)),
                ("fathers_occupation", models.CharField(blank=True, max_length=255)),
                ("fahers_aadhar_no", models.CharField(blank=True, max_length=255)),
                ("father_annual_income", models.CharField(blank=True, max_length=255)),
                ("father_qualification", models.CharField(blank=True, max_length=255)),
                ("father_pan_no", models.CharField(blank=True, max_length=255)),
                ("mothers_name", models.CharField(max_length=255)),
                ("mothers_email", models.CharField(blank=True, max_length=255)),
                ("mothers_mob_no", models.CharField(blank=True, max_length=255)),
                ("mothers_occupation", models.CharField(blank=True, max_length=255)),
                ("mothers_aadhar_no", models.CharField(blank=True, max_length=255)),
                ("mother_annual_income", models.CharField(blank=True, max_length=255)),
                ("mother_qualification", models.CharField(blank=True, max_length=255)),
                ("mother_pan_no", models.CharField(blank=True, max_length=255)),
                ("guardian_name", models.CharField(blank=True, max_length=255)),
                ("guardian_mobile", models.CharField(blank=True, max_length=255)),
                ("guardian_relation", models.CharField(blank=True, max_length=255)),
                ("fee_deposited_by", models.CharField(blank=True, max_length=255)),
                ("sms_mob_no", models.CharField(blank=True, max_length=255)),
                (
                    "child_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institute.childstatus",
                    ),
                ),
                (
                    "discount_scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institute.discountscheme",
                    ),
                ),
                (
                    "student_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institute.studenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
