# Generated by Django 5.0.6 on 2024-08-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="roll_number",
            field=models.CharField(default="123/234", max_length=10),
            preserve_default=False,
        ),
    ]
