# Generated by Django 5.0.6 on 2024-07-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("scholar_register", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="institute",
            field=models.ForeignKey(
                default="226",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
