# Generated by Django 4.2.13 on 2024-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='caution_money',
            field=models.IntegerField(),
        ),
    ]
