# Generated by Django 4.2.13 on 2024-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='maximum_marks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='obtain_marks',
            field=models.IntegerField(blank=True),
        ),
    ]
