# Generated by Django 5.0.1 on 2024-09-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_register', '0002_studentcomplaintsorsuggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcomplaintsorsuggestions',
            name='suggestion_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('Non Academic', 'Non-Academic')], max_length=200),
        ),
    ]
