# Generated by Django 4.2.13 on 2024-07-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_register', '0002_alter_studentprofile_maximum_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_deactivae',
            field=models.DateField(blank=True),
        ),
    ]
