# Generated by Django 5.0.6 on 2024-07-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_institute_user_id"),
        ("scholar_register", "0002_studentprofile_institute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_id",
                to="accounts.institute",
            ),
        ),
    ]
