# Generated by Django 4.2.13 on 2024-07-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
        ('scholar_register', '0002_alter_studentprofile_installment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='installment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.feeinstallments'),
        ),
    ]
