# Generated by Django 5.0.6 on 2024-07-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_register", "0002_remove_studentprofile_child_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentparents",
            old_name="fahers_aadhar_no",
            new_name="fathers_aadhar_no",
        ),
    ]
