# Generated by Django 5.0.6 on 2024-08-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_register", "0002_studentprofile_roll_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="amount",
        ),
    ]
