# Generated by Django 5.0.1 on 2024-09-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scholar_register', '0003_alter_studentcomplaintsorsuggestions_suggestion_type'),
        ('teacher_management', '0007_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Reject', 'reject'), ('Submitted', 'submitted')], default='pending', max_length=30)),
                ('remarks', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('attachment', models.FileField(upload_to='documents/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_branch', to='accounts.institutebranch')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_institute', to='accounts.institute')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_employee', to='teacher_management.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_session', to='accounts.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_student', to='scholar_register.studentprofile')),
            ],
        ),
    ]
