# Generated by Django 5.0.6 on 2024-07-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scholar_register",
            "0003_rename_fahers_aadhar_no_studentparents_fathers_aadhar_no",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="scholar_register.studentparents",
            ),
            preserve_default=False,
        ),
    ]
