# Generated by Django 4.2.13 on 2024-07-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_register', '0003_alter_studentprofile_installment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='institute',
        ),
    ]
