# Generated by Django 4.2.15 on 2024-08-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scholar_register', '0003_remove_studentprofile_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_branch', to='accounts.institutebranch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='ttendance_session', to='accounts.academicsession'),
            preserve_default=False,
        ),
    ]
