# Generated by Django 5.0.6 on 2024-07-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_institutebranch_institute"),
        ("scholar_register", "0004_alter_studentparents_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="institute",
        ),
        migrations.AddField(
            model_name="studentparents",
            name="institute",
            field=models.ForeignKey(
                default="136",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_id",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
