# Generated by Django 5.0.1 on 2024-09-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_register', '0004_assignment_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='assignment_submission',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assignment_submission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_student', to='scholar_register.studentprofile'),
        ),
    ]
