# Generated by Django 5.0.6 on 2024-07-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_register", "0004_remove_studentprofile_user_studentprofile_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="first_name",
            field=models.CharField(default="aman", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="last_name",
            field=models.CharField(default="jangid", max_length=100),
            preserve_default=False,
        ),
    ]
