# Generated by Django 5.0.6 on 2024-07-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_register", "0005_studentprofile_first_name_studentprofile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="scholar_register.studentparents",
            ),
        ),
    ]
