# Generated by Django 5.0.6 on 2024-07-25 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_institutebranch_institute"),
        ("scholar_register", "0005_remove_studentprofile_institute_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentparents",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_parent_id",
                to="accounts.institute",
            ),
        ),
        migrations.AlterField(
            model_name="studentparents",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_parent_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
