# Generated by Django 5.0.1 on 2024-09-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scholar_register', '0005_alter_assignment_submission_attachment_and_more'),
        ('teacher_management', '0008_rename_attachment_assignments_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment_submission',
            new_name='AssignmentSubmission',
        ),
    ]
