# Generated by Django 5.0.1 on 2024-10-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar_register', '0006_rename_assignment_submission_assignmentsubmission'),
        ('teacher_management', '0008_rename_attachment_assignments_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(default='13', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission_assignment', to='teacher_management.assignments'),
            preserve_default=False,
        ),
    ]
