# Generated by Django 5.0.6 on 2024-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_register", "0006_alter_studentparents_institute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="caution_money",
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=7),
            preserve_default=False,
        ),
    ]
