# Generated by Django 5.0.6 on 2024-07-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholar_register", "0007_studentprofile_caution_money"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="installment_mode",
        ),
    ]
