# Generated by Django 5.0.6 on 2024-08-09 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_institutebranch_is_active"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetable",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
    ]
