# Generated by Django 5.0.1 on 2024-09-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hr', '0001_initial'),
        ('institute', '0001_initial'),
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrinterview',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews_assign', to='teacher_management.employee'),
        ),
        migrations.AddField(
            model_name='hrinterview',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_interivew', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='hrinterview',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.category'),
        ),
        migrations.AddField(
            model_name='hrinterview',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_management.lmdepartmentmaster'),
        ),
        migrations.AddField(
            model_name='hrinterview',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_management.lmdesignationmaster'),
        ),
        migrations.AddField(
            model_name='hrinterview',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='hrinterview',
            name='reference',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews_reference', to='teacher_management.employee'),
        ),
        migrations.AddField(
            model_name='hrinterview',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_interview', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='teacher_management.employee'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_table_period', to='hr.classtimeperiod'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='institute.section'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_session', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='institute.standard'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='institute.subjects'),
        ),
    ]
