# Generated by Django 5.0.6 on 2024-07-30 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrinterview",
            name="institute",
            field=models.ForeignKey(
                default="373",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
