# Generated by Django 4.2.15 on 2024-10-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholar_register', '0001_initial'),
        ('examination', '0001_initial'),
        ('institute', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_standard', to='institute.standard'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_table_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_table_exam_type', to='examination.examtype'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_table_institute', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_table_session', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_table_standard', to='institute.standard'),
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_table_subject', to='institute.subjects'),
        ),
        migrations.AddField(
            model_name='examinationmarks',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_mark_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='examinationmarks',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_mark_exam_type', to='examination.examtype'),
        ),
        migrations.AddField(
            model_name='examinationmarks',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_mark_institute', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='examinationmarks',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_mark_section', to='institute.section'),
        ),
        migrations.AddField(
            model_name='examinationmarks',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_mark_session', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='examinationmarks',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_mark_standard', to='institute.standard'),
        ),
        migrations.AddField(
            model_name='examinationmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_mark_student_profile', to='scholar_register.studentprofile'),
        ),
        migrations.AddField(
            model_name='examinationmarks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_mark_subject', to='institute.subjects'),
        ),
    ]
