# Generated by Django 5.0.6 on 2024-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicsession",
            name="name",
            field=models.CharField(
                help_text="Name of the academic session", max_length=100
            ),
        ),
    ]
