# Generated by Django 4.2.15 on 2024-10-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CGPAResult',
        ),
    ]
