# Generated by Django 5.0.6 on 2024-08-01 09:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_duration",
                    models.IntegerField(
                        choices=[
                            (1, "1 month"),
                            (2, "2 months"),
                            (3, "3 months"),
                            (4, "4 months"),
                            (5, "5 months"),
                            (6, "6 months"),
                            (7, "7 months"),
                            (8, "8 months"),
                            (9, "9 months"),
                            (10, "10 months"),
                            (11, "11 months"),
                            (12, "12 months"),
                        ],
                        default=12,
                        help_text="Duration of the academic session in months",
                    ),
                ),
                (
                    "session_start_month",
                    models.IntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        help_text="Month when the academic session starts",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the academic session",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
                "ordering": ["-session_start_month"],
            },
        ),
        migrations.AddField(
            model_name="institute",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_session",
                to="accounts.academicsession",
            ),
        ),
    ]
