# Generated by Django 5.0.6 on 2024-08-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_academicsession_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutebranch",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
