# Generated by Django 5.0.6 on 2024-08-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_academicsession_institute_session"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicsession",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="institute",
            options={},
        ),
        migrations.RemoveField(
            model_name="institute",
            name="session",
        ),
        migrations.AddField(
            model_name="academicsession",
            name="institute",
            field=models.ForeignKey(
                default="121",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicsession",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="academicsession",
            name="start_date",
            field=models.DateField(default='2022-7-1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="academicsession",
            name="session_duration",
            field=models.IntegerField(
                choices=[
                    (1, "1 month"),
                    (2, "2 months"),
                    (3, "3 months"),
                    (4, "4 months"),
                    (5, "5 months"),
                    (6, "6 months"),
                    (7, "7 months"),
                    (8, "8 months"),
                    (9, "9 months"),
                    (10, "10 months"),
                    (11, "11 months"),
                    (12, "12 months"),
                ],
                default=6,
                help_text="Duration of the academic session in months",
            ),
        ),
    ]
