# Generated by Django 5.0.6 on 2024-07-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_institute_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institute",
            old_name="branch_name",
            new_name="number_of_branches",
        ),
    ]
