# Generated by Django 5.0.6 on 2024-07-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_branch_name_institute_number_of_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituteBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                (
                    "instutute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.institute",
                    ),
                ),
            ],
        ),
    ]
