# Generated by Django 5.0.6 on 2024-06-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_teacher_institute_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
