# Generated by Django 5.0.6 on 2024-07-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_institutebranch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institutebranch",
            old_name="instutute",
            new_name="institute",
        ),
    ]
