# Generated by Django 5.0.6 on 2024-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Institute'), ('2', 'Faculty'), ('3', 'Student')], null=True),
        ),
    ]
