# Generated by Django 5.0.6 on 2024-07-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_instutute_institutebranch_institute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutebranch",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch",
                to="accounts.institute",
            ),
        ),
    ]
