# Generated by Django 4.2.15 on 2024-10-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('due_amount', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_due_date', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paying_amount', models.IntegerField()),
                ('installment_frequency', models.CharField(choices=[('Half-Yearly', 'Half-Yearly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('No Installement', 'No Installement')], max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_payment_branch', to='accounts.institutebranch')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees_module.feestructure')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_payment_session', to='accounts.academicsession')),
            ],
        ),
    ]
