# Generated by Django 5.0.1 on 2024-09-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fees_module', '0001_initial'),
        ('institute', '0001_initial'),
        ('scholar_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='standard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_standard', to='institute.standard'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_payment_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees_module.feestructure'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_payment_session', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar_register.studentprofile'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='student_fee_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees_module.studentfeepayment'),
        ),
    ]
