# Generated by Django 5.0.6 on 2024-08-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_academicsession_options_and_more"),
        ("fees_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feestructure",
            name="session",
            field=models.OneToOneField(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
    ]
