# Generated by Django 5.0.6 on 2024-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeepayment",
            name="paying_amount",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
