# Generated by Django 5.0.6 on 2024-08-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_academicsession_name"),
        ("fees_module", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feestructure",
            name="institute",
        ),
        migrations.AddField(
            model_name="feestructure",
            name="branch",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structure",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
    ]
