# Generated by Django 5.0.6 on 2024-07-31 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees_module", "0001_initial"),
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="standard",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="institute.standard"
            ),
        ),
    ]
