# Generated by Django 4.2.15 on 2024-10-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees_module', '0001_initial'),
        ('scholar_register', '0001_initial'),
        ('institute', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar_register.studentprofile'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='student_fee_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees_module.studentfeepayment'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_institute', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_session', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='standard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure_standard', to='institute.standard'),
        ),
    ]
