# Generated by Django 5.0.6 on 2024-07-31 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("fees_module", "0002_alter_feestructure_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="feestructure",
            name="institute",
            field=models.ForeignKey(
                default="976",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structure",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
