# Generated by Django 5.0.6 on 2024-08-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("fees_module", "0002_studentfeepayment_paying_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeepayment",
            name="branch",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_fee_payment_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentfeepayment",
            name="session",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_fee_payment_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
    ]
