# Generated by Django 5.0.6 on 2024-08-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_academicsession_name"),
        ("fees_module", "0002_remove_feestructure_institute_feestructure_branch"),
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structure_branch",
                to="accounts.institutebranch",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structure_session",
                to="accounts.academicsession",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="standard",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structure_standard",
                to="institute.standard",
            ),
        ),
    ]
