# Generated by Django 4.2.13 on 2024-07-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_module', '0002_paymentschedule_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeepayment',
            name='installment_frequency',
            field=models.CharField(choices=[('Half-Yearly', 'Half-Yearly'), ('Monthly', 'Monthly'), ('No Installement', 'No Installement')], max_length=20),
        ),
    ]
