# Generated by Django 5.0.6 on 2024-08-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_academicsession_options_and_more"),
        ("fees_module", "0003_alter_feestructure_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="session",
            field=models.ForeignKey(
                default="27",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_schedule",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
    ]
