# Generated by Django 4.2.13 on 2024-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_module', '0003_alter_studentfeepayment_installment_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
