# Generated by Django 5.0.6 on 2024-08-08 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_institutebranch_is_active"),
        ("fees_module", "0004_feestructure_institute"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_schedule_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
    ]
