# Generated by Django 4.2.13 on 2024-07-25 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fees_module', '0004_alter_paymentschedule_payment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=5000.00, max_digits=10),
            preserve_default=False,
        ),
    ]
