# Generated by Django 4.2.13 on 2024-07-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_module', '0005_paymentschedule_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
