# Generated by Django 4.2.13 on 2024-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_module', '0007_alter_studentfeepayment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='amount_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='due_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
