# Generated by Django 4.2.13 on 2024-07-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_module', '0008_alter_paymentschedule_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeepayment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentfeepayment',
            name='start_date',
        ),
    ]
