# Generated by Django 4.2.13 on 2024-07-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_master', to='teacher_management.lmcategorymaster'),
        ),
    ]
