# Generated by Django 5.0.6 on 2024-07-23 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_institute_user_id"),
        ("teacher_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="institute",
            field=models.ForeignKey(
                default="226",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
