# Generated by Django 5.0.6 on 2024-07-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemaster',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='Designation',
            new_name='designation',
        ),
    ]
