# Generated by Django 5.0.1 on 2024-09-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('institute', '0002_initial'),
        ('teacher_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmcategorymaster',
            name='session',
        ),
        migrations.RemoveField(
            model_name='lmdepartmentmaster',
            name='session',
        ),
        migrations.RemoveField(
            model_name='lmdesignationmaster',
            name='session',
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_branch', to='accounts.institutebranch')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_institute', to='accounts.institute')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_section', to='institute.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_session', to='accounts.academicsession')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_standard', to='institute.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_subjects', to='institute.subjects')),
            ],
        ),
    ]
