# Generated by Django 5.0.6 on 2024-07-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("teacher_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lmcategorymaster",
            name="institute",
            field=models.ForeignKey(
                default="373",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lmcategory",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmdepartmentmaster",
            name="institute",
            field=models.ForeignKey(
                default="373",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lmdepartment",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmdesignationmaster",
            name="institute",
            field=models.ForeignKey(
                default="373",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lmdesignation",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
