# Generated by Django 5.0.6 on 2024-08-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_institutebranch_is_active"),
        ("teacher_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lmcategorymaster",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_category_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmcategorymaster",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_category_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmdepartmentmaster",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_department_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmdepartmentmaster",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_department_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmdesignationmaster",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_designation_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmdesignationmaster",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_designation_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
    ]
