# Generated by Django 5.0.6 on 2024-08-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_institutebranch_is_active"),
        (
            "teacher_management",
            "0002_lmcategorymaster_branch_lmcategorymaster_session_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeeattendance",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_attendance_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeeattendance",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_attendance_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeemaster",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_master_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employeemaster",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_master_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmattendancetype",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_attendance_type_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmattendancetype",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_attendance_type_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmholidaylist",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_holiday_list_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lmholidaylist",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lm_holiday_list_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
    ]
