# Generated by Django 5.0.1 on 2024-08-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0002_lmholidaylist_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='confirm_email',
            new_name='email',
        ),
    ]
