# Generated by Django 4.2.13 on 2024-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0002_alter_employeemaster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='reliving_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
