# Generated by Django 4.2.13 on 2024-06-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0002_lmdesignationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmDepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
