# Generated by Django 5.0.6 on 2024-07-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
        ('teacher_management', '0002_rename_department_employeemaster_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='category_cast',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='institute.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_management.lmcategorymaster'),
        ),
    ]
