# Generated by Django 5.0.6 on 2024-07-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_management", "0002_employee_institute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher_management.employeemaster",
            ),
        ),
    ]
