# Generated by Django 5.0.1 on 2024-09-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0002_remove_lmcategorymaster_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmattendancetype',
            name='session',
        ),
    ]
