# Generated by Django 5.0.6 on 2024-07-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("teacher_management", "0002_lmcategorymaster_institute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lmholidaylist",
            name="institute",
            field=models.ForeignKey(
                default="373",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lmholiday",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
