# Generated by Django 5.0.6 on 2024-07-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_management", "0003_alter_employee_employee_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="employee_name",
            new_name="employee_details",
        ),
    ]
