# Generated by Django 4.2.13 on 2024-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0003_lmdepartmentmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('nature', models.CharField(max_length=100)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
