# Generated by Django 5.0.6 on 2024-07-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0003_remove_employeemaster_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='join_date',
            field=models.DateField(auto_created=True),
        ),
    ]
