# Generated by Django 4.2.13 on 2024-07-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0003_alter_employeemaster_reliving_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='reliving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
