# Generated by Django 5.0.6 on 2024-07-30 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_management", "0003_lmholidaylist_institute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_details",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to="teacher_management.employeemaster",
            ),
        ),
    ]
