# Generated by Django 5.0.1 on 2024-09-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0004_alter_employee_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='employee',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='live_class_employee', to='teacher_management.employee'),
            preserve_default=False,
        ),
    ]
