# Generated by Django 5.0.6 on 2024-07-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_institutebranch_institute"),
        ("teacher_management", "0004_rename_employee_name_employee_employee_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeemaster",
            name="institute",
            field=models.ForeignKey(
                default="866",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
