# Generated by Django 5.0.6 on 2024-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0004_alter_employeemaster_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='emp_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='prefix',
            field=models.CharField(max_length=10),
        ),
    ]
