# Generated by Django 4.2.13 on 2024-06-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0004_attendancetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceType',
            new_name='LmAttendanceType',
        ),
    ]
