# Generated by Django 5.0.1 on 2024-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0005_liveclass_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
