# Generated by Django 4.2.13 on 2024-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0005_rename_attendancetype_lmattendancetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmattendancetype',
            name='nature',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Present', max_length=100),
        ),
    ]
