# Generated by Django 5.0.1 on 2024-09-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('institute', '0002_initial'),
        ('teacher_management', '0006_liveclass_class_date_liveclass_class_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('Attachment', models.FileField(upload_to='documents/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_branch', to='accounts.institutebranch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_employee', to='teacher_management.employee')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_institute', to='accounts.institute')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_section', to='institute.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_session', to='accounts.academicsession')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_standard', to='institute.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_subjects', to='institute.subjects')),
            ],
        ),
    ]
