# Generated by Django 5.0.6 on 2024-07-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0006_employeemaster_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemaster',
            old_name='Passport_no',
            new_name='Pass_port_no',
        ),
        migrations.RenameField(
            model_name='employeemaster',
            old_name='passpost_end_date',
            new_name='pass_port_end_date',
        ),
    ]
