# Generated by Django 5.0.1 on 2024-09-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0007_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Attachment',
            new_name='attachment',
        ),
    ]
