# Generated by Django 5.0.1 on 2024-10-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_management', '0008_rename_attachment_assignments_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='title',
            field=models.CharField(default='hello', max_length=40),
            preserve_default=False,
        ),
    ]
