# Generated by Django 4.2.15 on 2024-08-26 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_menu_institute', to='accounts.institute')),
            ],
        ),
    ]
