# Generated by Django 5.0.6 on 2024-07-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        choices=[("2", "Teacher"), ("1", "Institute")], default="1"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("Description", models.TextField(max_length=1000)),
                ("document", models.FileField(upload_to="documents/")),
            ],
        ),
    ]
