# Generated by Django 5.0.6 on 2024-07-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Branches",
        ),
    ]
