# Generated by Django 5.0.6 on 2024-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='can_add',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='can_print',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='supersubmenu',
            name='can_add',
        ),
        migrations.RemoveField(
            model_name='supersubmenu',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='supersubmenu',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='supersubmenu',
            name='can_print',
        ),
        migrations.RemoveField(
            model_name='supersubmenu',
            name='can_view',
        ),
        migrations.AddField(
            model_name='permission',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('role', 'menu', 'submenu', 'supersubmenu'), name='unique_role_menu_submenu_supersubmenu'),
        ),
    ]
