# Generated by Django 4.2.13 on 2024-07-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='gellery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
