# Generated by Django 5.0.6 on 2024-07-31 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instituterole",
            name="institute",
            field=models.ForeignKey(
                default="121",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_role",
                to="accounts.institute",
            ),
            preserve_default=False,
        ),
    ]
