# Generated by Django 4.2.13 on 2024-07-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='standard',
            field=models.ForeignKey(default='340', on_delete=django.db.models.deletion.CASCADE, related_name='section', to='institute.standard'),
            preserve_default=False,
        ),
    ]
