# Generated by Django 5.0.6 on 2024-06-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='auto_admi_number',
            new_name='auto_admin_number',
        ),
    ]
