# Generated by Django 4.2.13 on 2024-07-04 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsForClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('All', 'All'), ('Selected', 'Selected')], default='Selected')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.standard')),
            ],
        ),
        migrations.DeleteModel(
            name='SubjectForClassGroup',
        ),
    ]
