# Generated by Django 5.0.6 on 2024-08-07 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_academicsession_name"),
        ("institute", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="standard",
            name="branch",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
    ]
