# Generated by Django 5.0.1 on 2024-09-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('institute', '0001_initial'),
        ('scholar_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scholar_register.studentprofile'),
        ),
        migrations.AddField(
            model_name='childstatus',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_status', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='classgroups',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='classwisesubjects',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wise_subjects_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='classwisesubjects',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wise_subjects', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='classwisesubjects',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wise_subjects', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='custommenu',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_menu_institute', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='discountscheme',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_scheme_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='discountscheme',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_scheme', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='discountscheme',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_scheme', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='documents',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='documents',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='documents',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='documentsrequired',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_required_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='documentsrequired',
            name='document_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.documents'),
        ),
        migrations.AddField(
            model_name='documentsrequired',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_required', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='documentsrequired',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_required', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='enquirytype',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_type', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='familirelation',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relation', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='feeheads',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_heads', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='feeinstallments',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_installment_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='feeinstallments',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_installments', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='feeinstallments',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_installment_session', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='galleryitems',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='galleryitems',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_gallery', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='galleryitems',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='house',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='house',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='house',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='House', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='instituterole',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_role_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='instituterole',
            name='branches',
            field=models.ManyToManyField(related_name='roles', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='instituterole',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_role', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='leavingreasontc',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaving_reason', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='lomsignature',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lom_signature', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='lomsignature',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lom_signature', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='instituterole',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.mainmenu'),
        ),
        migrations.AddField(
            model_name='medium',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='mothertoungue',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maothe_tongue', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='nameofsainikschool',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_sainik_school', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='nameofthebank',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_bank', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='nextclass',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_class', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_mode', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='permission',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.mainmenu'),
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='institute.instituterole'),
        ),
        migrations.AddField(
            model_name='reference',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='reference',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='reference',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_session', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='religion',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='religion', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='section',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='section',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.section'),
        ),
        migrations.AddField(
            model_name='standard',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='standard',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='section',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='institute.standard'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.standard'),
        ),
        migrations.AddField(
            model_name='studenttype',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_type', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.standard'),
        ),
        migrations.AddField(
            model_name='classwisesubjects',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_wise_subjects_subject', to='institute.subjects'),
        ),
        migrations.AddField(
            model_name='subjectsforclassgroup',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_for_class_group_branch', to='accounts.institutebranch'),
        ),
        migrations.AddField(
            model_name='subjectsforclassgroup',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_for_class_groups', to='accounts.institute'),
        ),
        migrations.AddField(
            model_name='subjectsforclassgroup',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.subjects'),
        ),
        migrations.AddField(
            model_name='subjectsforclassgroup',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_for_class_groups', to='accounts.academicsession'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='institute.mainmenu'),
        ),
        migrations.AddField(
            model_name='permission',
            name='submenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.submenu'),
        ),
        migrations.AddField(
            model_name='supersubmenu',
            name='submenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersubmenus', to='institute.submenu'),
        ),
        migrations.AddField(
            model_name='permission',
            name='supersubmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institute.supersubmenu'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('role', 'menu', 'submenu', 'supersubmenu'), name='unique_role_menu_submenu_supersubmenu'),
        ),
    ]
