# Generated by Django 5.0.6 on 2024-08-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_academicsession_name"),
        ("institute", "0002_standard_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="branch",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
    ]
