# Generated by Django 5.0.6 on 2024-07-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0002_notificationmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationmodel",
            old_name="Description",
            new_name="description",
        ),
    ]
