# Generated by Django 5.0.6 on 2024-08-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_academicsession_options_and_more"),
        ("institute", "0002_instituterole_institute"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="session",
            field=models.ForeignKey(
                default="32",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjects",
            name="session",
            field=models.ForeignKey(
                default="32",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
    ]
