# Generated by Django 5.0.6 on 2024-06-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rename_auto_admi_number_institute_auto_admin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='institute.institute')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
