# Generated by Django 4.2.13 on 2024-07-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_galleryitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitems',
            name='file',
        ),
        migrations.AddField(
            model_name='galleryitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gellery/'),
        ),
        migrations.AddField(
            model_name='galleryitems',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gellery/'),
        ),
    ]
