# Generated by Django 5.0.6 on 2024-06-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_nextclass_role_section_subjectforclassgroup_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
