# Generated by Django 4.2.13 on 2024-08-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_alter_subjectsforclassgroup_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectForClassGroup',
        ),
    ]
