# Generated by Django 5.0.1 on 2024-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_standard_result_type_gradingsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsystem',
            name='marks_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='marks_to',
            field=models.IntegerField(),
        ),
    ]
