# Generated by Django 5.0.6 on 2024-06-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='change_zoom_url',
        ),
    ]
