# Generated by Django 4.2.13 on 2024-07-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('institute', '0004_galleryitems_url_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitems',
            name='institute',
            field=models.ForeignKey(default='124', on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='accounts.institute'),
            preserve_default=False,
        ),
    ]
