# Generated by Django 5.0.6 on 2024-08-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_institutebranch_is_active"),
        ("institute", "0004_chatmessage_branch_classwisesubjects_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="branch",
            field=models.ForeignKey(
                default="21",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_branch",
                to="accounts.institutebranch",
            ),
            preserve_default=False,
        ),
    ]
