# Generated by Django 4.2.13 on 2024-07-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_galleryitems_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitems',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
