# Generated by Django 5.0.6 on 2024-08-09 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_institutebranch_is_active"),
        ("institute", "0005_house_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="session",
            field=models.ForeignKey(
                default="10",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reference_session",
                to="accounts.academicsession",
            ),
            preserve_default=False,
        ),
    ]
