# Generated by Django 5.0.6 on 2024-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_caste_category_childstatus_classgroups_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LomSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_name', models.CharField(max_length=100)),
                ('signature_heading', models.CharField(max_length=100)),
            ],
        ),
    ]
