# Generated by Django 4.2.13 on 2024-08-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_chatmessage_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='reciever',
            new_name='receiever',
        ),
    ]
