# Generated by Django 4.2.13 on 2024-08-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_rename_reciever_chatmessage_receiever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiever',
            new_name='receiver',
        ),
    ]
